#pragma once

enum class PLAYER_ID {
  LOCAL = 0,
  NEUTRAL_PASSIVE = 15,
  NEUTRAL_AGGRESSIVE = 12,
};

enum class PLAYER_COLOR {
  RED = 0,
  BLUE = 1,
  CYAN = 2,
  PURPLE = 3,
  YELLOW = 4,
  ORANGE = 5,
  GREEN = 6,
  PINK = 7,
  LIGHT_GRAY = 8,
  LIGHT_BLUE = 9,
  AQUA = 10,
  BROWN = 11,
};

enum class RACE {
  HUMAN = 1,
  ORC = 2,
  UNDEAD = 3,
  NIGHTELF = 4,
  DEMON = 5,
  OTHER = 7,
};

enum class GAME_RESULT {
  VICTORY,
  DEFEAT,
  TIE,
  NEUTRAL,
};

enum class ALLIANCE_TYPE {
  PASSIVE,
  HELP_REQUEST,
  HELP_RESPONSE,
  SHARED_XP,
  SHARED_SPELLS,
  SHARED_VISION,
  SHARED_CONTROL,
  SHARED_ADVANCED_CONTROL,
  RESCUABLE,
  SHARED_VISION_FORCED,
};

enum class DLC_VERSION {
  REIGN_OF_CHAOS,
  FROZEN_THRONE,
};

enum class ATTACK_TYPE {
  NORMAL,
  MELEE,
  PIERCE,
  SIEGE,
  MAGIC,
  CHAOS,
  HERO,
};

enum class DAMAGE_TYPE {
  UNKNOWN = 0,
  NORMAL = 4,
  ENHANCED = 5,
  FIRE = 8,
  COLD = 9,
  LIGHTNING = 10,
  POISON = 11,
  DISEASE = 12,
  DIVINE = 13,
  MAGIC = 14,
  SONIC = 15,
  ACID = 16,
  FORCE = 17,
  DEATH = 18,
  MIND = 19,
  PLANT = 20,
  DEFENSIVE = 21,
  DEMOLITION = 22,
  SLOW_POISON = 23,
  SPIRIT_LINK = 24,
  SHADOW_STRIKE = 25,
  UNIVERSAL = 26,
};

enum class WEAPON_TYPE {
  WHOKNOWS = 0,
  METAL_LIGHT_CHOP = 1,
  METAL_MEDIUM_CHOP = 2,
  METAL_HEAVY_CHOP = 3,
  METAL_LIGHT_SLICE = 4,
  METAL_MEDIUM_SLICE = 5,
  METAL_HEAVY_SLICE = 6,
  METAL_MEDIUM_BASH = 7,
  METAL_HEAVY_BASH = 8,
  METAL_MEDIUM_STAB = 9,
  METAL_HEAVY_STAB = 10,
  WOOD_LIGHT_SLICE = 11,
  WOOD_MEDIUM_SLICE = 12,
  WOOD_HEAVY_SLICE = 13,
  WOOD_LIGHT_BASH = 14,
  WOOD_MEDIUM_BASH = 15,
  WOOD_HEAVY_BASH = 16,
  WOOD_LIGHT_STAB = 17,
  WOOD_MEDIUM_STAB = 18,
  CLAW_LIGHT_SLICE = 19,
  CLAW_MEDIUM_SLICE = 20,
  CLAW_HEAVY_SLICE = 21,
  AXE_MEDIUM_CHOP = 22,
  ROCK_HEAVY_BASH = 23,
};

enum class PATHING_TYPE {
  ANY,
  WALKABILITY,
  FLYABILITY,
  BUILDABILITY,
  PEONHARVESTPATHING,
  BLIGHTPATHING,
  FLOATABILITY,
  AMPHIBIOUSPATHING,
};

enum class PLAYER_SLOT_STATE {
  EMPTY,
  PLAYING,
  LEFT,
};

enum class GAME_STATE {
  DIVINE_INTERVENTION,
  DISCONNECTED,
  TIME_OF_DAY,
};

enum class PLAYER_STATE {
  GAME_RESULT,
  RESOURCE_GOLD,
  RESOURCE_LUMBER,
  RESOURCE_HERO_TOKENS,
  RESOURCE_FOOD_CAP,
  RESOURCE_FOOD_USED,
  FOOD_CAP_CEILING,
  GIVES_BOUNTY,
  ALLIED_VICTORY,
  PLACED,
  OBSERVER_ON_DEATH,
  OBSERVER,
  UNFOLLOWABLE,
  GOLD_UPKEEP_RATE,
  LUMBER_UPKEEP_RATE,
  GOLD_GATHERED,
  LUMBER_GATHERED,
  NO_CREEP_SLEEP = 25,
};

enum class UNIT_STATE {
  LIFE,
  MAX_LIFE,
  MANA,
  MAX_MANA,
};

enum class AI_DIFFICULTY {
  NEWBIE,
  NORMAL,
  INSANE,
};

enum class PLAYER_SCORE {
  UNITS_TRAINED,
  UNITS_KILLED,
  STRUCT_BUILT,
  STRUCT_RAZED,
  TECH_PERCENT,
  FOOD_MAXPROD,
  FOOD_MAXUSED,
  HEROES_KILLED,
  ITEMS_GAINED,
  MERCS_HIRED,
  GOLD_MINED_TOTAL,
  GOLD_MINED_UPKEEP,
  GOLD_LOST_UPKEEP,
  GOLD_LOST_TAX,
  GOLD_GIVEN,
  GOLD_RECEIVED,
  LUMBER_TOTAL,
  LUMBER_LOST_UPKEEP,
  LUMBER_LOST_TAX,
  LUMBER_GIVEN,
  LUMBER_RECEIVED,
  UNIT_TOTAL,
  HERO_TOTAL,
  RESOURCE_TOTAL,
  TOTAL,
};

enum class LIMIT_OP {
  LESS_THAN,
  LESS_THAN_OR_EQUAL,
  EQUAL,
  GREATER_THAN_OR_EQUAL,
  GREATER_THAN,
  NOT_EQUAL,
};

enum class UNIT_TYPE {
  HERO,
  DEAD,
  STRUCTURE,

  FLYING,
  GROUND,

  ATTACKS_FLYING,
  ATTACKS_GROUND,

  MELEE_ATTACKER,
  RANGED_ATTACKER,

  GIANT,
  SUMMONED,
  STUNNED,
  PLAGUED,
  SNARED,

  UNDEAD,
  MECHANICAL,
  PEON,
  SAPPER,
  TOWNHALL,
  ANCIENT,

  TAUREN,
  POISONED,
  POLYMORPHED,
  SLEEPING,
  RESISTANT,
  ETHEREAL,
  MAGIC_IMMUNE,
};

enum class ITEM_TYPE {
  PERMANENT,
  CHARGED,
  POWERUP,
  ARTIFACT,
  PURCHASABLE,
  CAMPAIGN,
  MISCELLANEOUS,
  UNKNOWN,
  ANY,
};
